spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.datasource.generate-unique-name: false
# spring.datasource.name: Video
spring.jpa.hibernate.ddl-auto: update
spring.jpa.generate-ddl: true
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true

logging.level.org.springframework.web: debug
logging.level.org.hibernate: error


camunda.bpm.admin-user:
  id: demo
  password: demo

rest.apikey: AIzaSyD9wD56NTeRERlt0QtOL-gkMreHvjtGUiA